# Generated by Django 5.0.4 on 2024-06-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='social_post_total_l_b22ce0_idx',
        ),
    ]
