# Generated by Django 5.0.4 on 2024-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_post_social_post_total_l_b22ce0_idx'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-total_likes'], name='social_post_total_l_b22ce0_idx'),
        ),
    ]
